---------------------------------------------

SELECT * FROM NOTA_FISCAL.CONTRIBUINTE;
SELECT * FROM NOTA_FISCAL.ENDERECO;
SELECT * FROM NOTA_FISCAL.DANFE;

/*
DELETE FROM NOTA_FISCAL.CONTRIBUINTE c WHERE c.CD_CONTRIBUINTE = '270000030';
DELETE FROM NOTA_FISCAL.ENDERECO e WHERE e.CD_CONTRIBUINTE = '270000030';

ALTER USER NOTA_FISCAL QUOTA UNLIMITED ON USERS;

DROP TABLE NOTA_FISCAL.DANFE;
DROP TABLE NOTA_FISCAL.ENDERECO;
DROP TABLE NOTA_FISCAL.CONTRIBUINTE;
*/

---------------------------------------------